import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  HeadingLevel,
  ShadingType,
} from 'docx';
import pptxgen from 'pptxgenjs';
import { saveAs } from 'file-saver';
import type { MeetingAgendaData } from './insightsAnalytics';

// Color palette for modern, fun design
const COLORS = {
  primary: '4F46E5',      // Indigo
  secondary: '7C3AED',    // Purple
  success: '14B8A6',      // Teal
  warning: 'F59E0B',      // Amber
  danger: 'F43F5E',       // Rose
  dark: '1E293B',         // Slate 800
  light: 'F8FAFC',        // Slate 50
  muted: '64748B',        // Slate 500
};

// ============ Word Document Generation ============

export const generateWordDocument = async (data: MeetingAgendaData): Promise<void> => {
  const doc = new Document({
    styles: {
      paragraphStyles: [
        {
          id: 'Title',
          name: 'Title',
          basedOn: 'Normal',
          next: 'Normal',
          run: {
            size: 56,
            bold: true,
            color: COLORS.primary,
          },
          paragraph: {
            spacing: { after: 300 },
            alignment: AlignmentType.CENTER,
          },
        },
      ],
    },
    sections: [
      {
        properties: {},
        children: [
          // Header
          new Paragraph({
            children: [
              new TextRun({
                text: 'DEPARTMENT CHAMPS',
                bold: true,
                size: 48,
                color: COLORS.primary,
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: 'Regional Performance Meeting',
                size: 32,
                color: COLORS.muted,
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),

          // Meeting Details
          createInfoBox([
            { label: 'Program', value: data.program },
            { label: 'Date', value: data.date },
            { label: 'Duration', value: '30 minutes' },
          ]),

          new Paragraph({ spacing: { after: 300 } }),

          // Department Overview
          new Paragraph({
            children: [
              new TextRun({
                text: 'Department Overview',
                bold: true,
                size: 28,
                color: COLORS.dark,
              }),
            ],
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),

          createStatsTable(data.overallStats),

          new Paragraph({ spacing: { after: 300 } }),

          // Section 1: T>P Opportunities
          createSectionHeader('1', 'T>P Improvement Opportunities', '10 min', COLORS.success),
          ...createRecommendationsParagraphs(data.tpRecommendations, 'passthroughs', COLORS.success),

          // Section 2: P>Q Opportunities
          createSectionHeader('2', 'P>Q Improvement Opportunities', '5 min', COLORS.secondary),
          ...createRecommendationsParagraphs(data.pqRecommendations, 'quotes', COLORS.secondary),

          // Section 3: Agent Performance
          createSectionHeader('3', 'Agent Performance Highlights', '10 min', COLORS.warning),

          new Paragraph({
            children: [
              new TextRun({
                text: 'Top Performers',
                bold: true,
                size: 24,
                color: COLORS.success,
              }),
            ],
            spacing: { before: 200, after: 150 },
          }),
          ...createAgentParagraphs(data.topAgents, true),

          new Paragraph({
            children: [
              new TextRun({
                text: 'Development Focus',
                bold: true,
                size: 24,
                color: COLORS.danger,
              }),
            ],
            spacing: { before: 300, after: 150 },
          }),
          ...createAgentParagraphs(data.bottomAgents, false),

          // Section 4: Actions
          createSectionHeader('4', 'Actions & Next Steps', '5 min', COLORS.primary),
          ...createActionItems(),

          // Footer
          new Paragraph({ spacing: { before: 600 } }),
          new Paragraph({
            children: [
              new TextRun({
                text: 'Generated by GTT KPI Report',
                size: 18,
                color: COLORS.muted,
                italics: true,
              }),
            ],
            alignment: AlignmentType.CENTER,
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `Department_Champs_${data.program.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.docx`);
};

function createInfoBox(items: { label: string; value: string }[]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: items.map(item =>
      new TableRow({
        children: [
          new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: item.label, bold: true, size: 22, color: COLORS.muted }),
                ],
              }),
            ],
            width: { size: 25, type: WidthType.PERCENTAGE },
            shading: { fill: 'F1F5F9', type: ShadingType.CLEAR },
            borders: {
              top: { style: BorderStyle.NONE },
              bottom: { style: BorderStyle.NONE },
              left: { style: BorderStyle.NONE },
              right: { style: BorderStyle.NONE },
            },
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: item.value, size: 22, color: COLORS.dark }),
                ],
              }),
            ],
            width: { size: 75, type: WidthType.PERCENTAGE },
            shading: { fill: 'F1F5F9', type: ShadingType.CLEAR },
            borders: {
              top: { style: BorderStyle.NONE },
              bottom: { style: BorderStyle.NONE },
              left: { style: BorderStyle.NONE },
              right: { style: BorderStyle.NONE },
            },
          }),
        ],
      })
    ),
  });
}

function createStatsTable(stats: MeetingAgendaData['overallStats']): Table {
  const statsItems = [
    { label: 'Total Trips', value: stats.totalTrips.toLocaleString() },
    { label: 'Passthroughs', value: stats.totalPassthroughs.toLocaleString() },
    { label: 'T>P Rate', value: `${stats.tpRate.toFixed(1)}%` },
    { label: 'Hot Pass Rate', value: `${stats.hotPassRate.toFixed(1)}%` },
    { label: 'P>Q Rate', value: `${stats.pqRate.toFixed(1)}%` },
    { label: 'Destinations', value: stats.destinationsTracked.toString() },
  ];

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: statsItems.slice(0, 3).map(item =>
          new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: item.value, bold: true, size: 28, color: COLORS.primary }),
                ],
                alignment: AlignmentType.CENTER,
              }),
              new Paragraph({
                children: [
                  new TextRun({ text: item.label, size: 18, color: COLORS.muted }),
                ],
                alignment: AlignmentType.CENTER,
              }),
            ],
            width: { size: 33, type: WidthType.PERCENTAGE },
            borders: {
              top: { style: BorderStyle.NONE },
              bottom: { style: BorderStyle.NONE },
              left: { style: BorderStyle.NONE },
              right: { style: BorderStyle.NONE },
            },
          })
        ),
      }),
      new TableRow({
        children: statsItems.slice(3).map(item =>
          new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: item.value, bold: true, size: 28, color: COLORS.secondary }),
                ],
                alignment: AlignmentType.CENTER,
              }),
              new Paragraph({
                children: [
                  new TextRun({ text: item.label, size: 18, color: COLORS.muted }),
                ],
                alignment: AlignmentType.CENTER,
              }),
            ],
            width: { size: 33, type: WidthType.PERCENTAGE },
            borders: {
              top: { style: BorderStyle.NONE },
              bottom: { style: BorderStyle.NONE },
              left: { style: BorderStyle.NONE },
              right: { style: BorderStyle.NONE },
            },
          })
        ),
      }),
    ],
  });
}

function createSectionHeader(num: string, title: string, duration: string, color: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({
        text: `${num}. ${title}`,
        bold: true,
        size: 28,
        color: color,
      }),
      new TextRun({
        text: `  (${duration})`,
        size: 22,
        color: COLORS.muted,
      }),
    ],
    spacing: { before: 400, after: 200 },
    border: {
      bottom: { style: BorderStyle.SINGLE, size: 6, color: color },
    },
  });
}

function createRecommendationsParagraphs(
  recommendations: MeetingAgendaData['tpRecommendations'],
  gainType: string,
  color: string
): Paragraph[] {
  if (recommendations.length === 0) {
    return [
      new Paragraph({
        children: [
          new TextRun({
            text: 'No significant improvement opportunities identified.',
            italics: true,
            color: COLORS.muted,
          }),
        ],
        spacing: { after: 200 },
      }),
    ];
  }

  return recommendations.flatMap((rec, i) => [
    new Paragraph({
      children: [
        new TextRun({ text: `${i + 1}. `, bold: true, color }),
        new TextRun({ text: rec.region, bold: true, size: 24 }),
      ],
      spacing: { before: 150 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `Current: ${rec.tpRate.toFixed(1)}%`, color: COLORS.danger }),
        new TextRun({ text: ` vs Avg: ${rec.departmentAvgRate.toFixed(1)}%`, color: COLORS.muted }),
        new TextRun({ text: `  |  Gap: ${Math.abs(rec.deviation).toFixed(1)}pp`, color: COLORS.muted }),
        new TextRun({ text: `  |  Volume: ${rec.trips}`, color: COLORS.muted }),
      ],
      spacing: { after: 50 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Potential: +${Math.round(rec.potentialGain)} ${gainType}`,
          color: COLORS.success,
          bold: true,
        }),
      ],
      spacing: { after: 200 },
    }),
  ]);
}

function createAgentParagraphs(
  agents: MeetingAgendaData['topAgents'] | MeetingAgendaData['bottomAgents'],
  isTop: boolean
): Paragraph[] {
  if (agents.length === 0) {
    return [
      new Paragraph({
        children: [
          new TextRun({ text: 'No agent data available.', italics: true, color: COLORS.muted }),
        ],
        spacing: { after: 200 },
      }),
    ];
  }

  return agents.flatMap((agent, i) => {
    const regions = isTop
      ? (agent as MeetingAgendaData['topAgents'][0]).regions
      : (agent as MeetingAgendaData['bottomAgents'][0]).focusRegions;
    const regionLabel = isTop ? 'Strong Regions' : 'Focus Regions';

    return [
      new Paragraph({
        children: [
          new TextRun({ text: `${i + 1}. `, bold: true }),
          new TextRun({ text: agent.name, bold: true, size: 24 }),
          new TextRun({ text: `  T>P: ${agent.tpRate.toFixed(1)}%`, color: isTop ? COLORS.success : COLORS.danger }),
          new TextRun({ text: `  |  ${agent.trips} trips`, color: COLORS.muted }),
        ],
        spacing: { before: 100 },
      }),
      ...(regions.length > 0
        ? [
            new Paragraph({
              children: [
                new TextRun({ text: `${regionLabel}: `, color: COLORS.muted, size: 20 }),
                new TextRun({ text: regions.join(', '), size: 20 }),
              ],
              spacing: { after: 150 },
            }),
          ]
        : []),
    ];
  });
}

function createActionItems(): Paragraph[] {
  const actions = [
    'Review training materials for focus destinations',
    'Schedule 1:1s with development focus agents',
    'Share best practices from top performers',
    'Update destination knowledge resources',
    'Set improvement targets for next review',
  ];

  return actions.map(action =>
    new Paragraph({
      children: [
        new TextRun({ text: '☐ ', size: 24 }),
        new TextRun({ text: action, size: 22 }),
      ],
      spacing: { after: 100 },
    })
  );
}

// ============ PowerPoint Generation ============

export const generatePowerPoint = async (data: MeetingAgendaData): Promise<void> => {
  const pptx = new pptxgen();

  // Set presentation properties
  pptx.author = 'GTT KPI Report';
  pptx.title = `Department Champs - ${data.program}`;
  pptx.subject = 'Regional Performance Meeting';

  // Define master slide
  pptx.defineSlideMaster({
    title: 'CHAMP_MASTER',
    background: { color: '0F172A' }, // Dark slate background
    objects: [
      {
        placeholder: {
          options: { name: 'title', type: 'title', x: 0.5, y: 0.3, w: 9, h: 0.8 },
          text: '',
        },
      },
    ],
  });

  // Slide 1: Title Slide
  const slide1 = pptx.addSlide();
  slide1.background = { color: '0F172A' };

  slide1.addText('DEPARTMENT CHAMPS', {
    x: 0.5,
    y: 1.5,
    w: 9,
    h: 1,
    fontSize: 44,
    bold: true,
    color: COLORS.light,
    align: 'center',
  });

  slide1.addText('Regional Performance', {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 0.8,
    fontSize: 32,
    color: COLORS.primary,
    align: 'center',
  });

  slide1.addShape('rect', {
    x: 3,
    y: 3.5,
    w: 4,
    h: 0.05,
    fill: { color: COLORS.primary },
  });

  slide1.addText(data.program, {
    x: 0.5,
    y: 3.8,
    w: 9,
    h: 0.6,
    fontSize: 28,
    color: COLORS.warning,
    align: 'center',
    bold: true,
  });

  slide1.addText(data.date, {
    x: 0.5,
    y: 4.5,
    w: 9,
    h: 0.5,
    fontSize: 18,
    color: COLORS.muted,
    align: 'center',
  });

  // Slide 2: Agenda Overview
  const slide2 = pptx.addSlide();
  slide2.background = { color: '0F172A' };

  slide2.addText('Meeting Agenda', {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.8,
    fontSize: 36,
    bold: true,
    color: COLORS.light,
  });

  const agendaItems = [
    { time: '10 min', title: 'T>P Improvement Opportunities', color: COLORS.success },
    { time: '5 min', title: 'P>Q Improvement Opportunities', color: COLORS.secondary },
    { time: '10 min', title: 'Agent Performance Highlights', color: COLORS.warning },
    { time: '5 min', title: 'Actions & Next Steps', color: COLORS.primary },
  ];

  agendaItems.forEach((item, i) => {
    const y = 1.3 + i * 1.1;

    slide2.addShape('rect', {
      x: 0.5,
      y: y,
      w: 9,
      h: 0.9,
      fill: { color: '1E293B' },
      line: { color: item.color, width: 2 },
    });

    slide2.addText(`${i + 1}`, {
      x: 0.7,
      y: y + 0.15,
      w: 0.6,
      h: 0.6,
      fontSize: 24,
      bold: true,
      color: item.color,
      align: 'center',
      valign: 'middle',
    });

    slide2.addText(item.title, {
      x: 1.5,
      y: y + 0.2,
      w: 6.5,
      h: 0.5,
      fontSize: 22,
      color: COLORS.light,
    });

    slide2.addText(item.time, {
      x: 8,
      y: y + 0.25,
      w: 1.3,
      h: 0.4,
      fontSize: 14,
      color: COLORS.muted,
      align: 'right',
    });
  });

  // Slide 3: Department Overview
  const slide3 = pptx.addSlide();
  slide3.background = { color: '0F172A' };

  slide3.addText('Department Overview', {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.8,
    fontSize: 36,
    bold: true,
    color: COLORS.light,
  });

  const stats = [
    { label: 'Total Trips', value: data.overallStats.totalTrips.toLocaleString(), color: COLORS.light },
    { label: 'Passthroughs', value: data.overallStats.totalPassthroughs.toLocaleString(), color: COLORS.light },
    { label: 'T>P Rate', value: `${data.overallStats.tpRate.toFixed(1)}%`, color: COLORS.success },
    { label: 'Hot Pass Rate', value: `${data.overallStats.hotPassRate.toFixed(1)}%`, color: COLORS.warning },
    { label: 'P>Q Rate', value: `${data.overallStats.pqRate.toFixed(1)}%`, color: COLORS.secondary },
    { label: 'Destinations', value: data.overallStats.destinationsTracked.toString(), color: COLORS.light },
  ];

  stats.forEach((stat, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const x = 0.5 + col * 3.2;
    const y = 1.3 + row * 2;

    slide3.addShape('rect', {
      x: x,
      y: y,
      w: 2.9,
      h: 1.7,
      fill: { color: '1E293B' },
      line: { color: '334155', width: 1 },
    });

    slide3.addText(stat.value, {
      x: x,
      y: y + 0.3,
      w: 2.9,
      h: 0.8,
      fontSize: 36,
      bold: true,
      color: stat.color,
      align: 'center',
    });

    slide3.addText(stat.label, {
      x: x,
      y: y + 1.1,
      w: 2.9,
      h: 0.4,
      fontSize: 14,
      color: COLORS.muted,
      align: 'center',
    });
  });

  // Slide 4: T>P Opportunities
  const slide4 = pptx.addSlide();
  slide4.background = { color: '0F172A' };

  slide4.addText('T>P Improvement Opportunities', {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.8,
    fontSize: 32,
    bold: true,
    color: COLORS.success,
  });

  if (data.tpRecommendations.length > 0) {
    data.tpRecommendations.forEach((rec, i) => {
      const y = 1.2 + i * 1.5;

      slide4.addShape('rect', {
        x: 0.5,
        y: y,
        w: 9,
        h: 1.3,
        fill: { color: '1E293B' },
        line: { color: COLORS.success, width: 1, dashType: 'solid' },
      });

      slide4.addText(`${i + 1}`, {
        x: 0.7,
        y: y + 0.35,
        w: 0.5,
        h: 0.6,
        fontSize: 20,
        bold: true,
        color: COLORS.success,
      });

      slide4.addText(rec.region, {
        x: 1.3,
        y: y + 0.15,
        w: 5,
        h: 0.5,
        fontSize: 22,
        bold: true,
        color: COLORS.light,
      });

      slide4.addText(`+${Math.round(rec.potentialGain)} potential PT`, {
        x: 7,
        y: y + 0.15,
        w: 2.3,
        h: 0.5,
        fontSize: 16,
        bold: true,
        color: COLORS.success,
        align: 'right',
      });

      slide4.addText(
        `Current: ${rec.tpRate.toFixed(1)}%  |  Avg: ${rec.departmentAvgRate.toFixed(1)}%  |  Gap: ${Math.abs(rec.deviation).toFixed(1)}pp  |  ${rec.trips} trips`,
        {
          x: 1.3,
          y: y + 0.7,
          w: 8,
          h: 0.4,
          fontSize: 14,
          color: COLORS.muted,
        }
      );
    });
  } else {
    slide4.addText('No significant T>P improvement opportunities identified.', {
      x: 0.5,
      y: 2,
      w: 9,
      h: 0.5,
      fontSize: 18,
      color: COLORS.muted,
      align: 'center',
      italic: true,
    });
  }

  // Slide 5: P>Q Opportunities
  const slide5 = pptx.addSlide();
  slide5.background = { color: '0F172A' };

  slide5.addText('P>Q Improvement Opportunities', {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.8,
    fontSize: 32,
    bold: true,
    color: COLORS.secondary,
  });

  if (data.pqRecommendations.length > 0) {
    data.pqRecommendations.forEach((rec, i) => {
      const y = 1.2 + i * 1.5;

      slide5.addShape('rect', {
        x: 0.5,
        y: y,
        w: 9,
        h: 1.3,
        fill: { color: '1E293B' },
        line: { color: COLORS.secondary, width: 1, dashType: 'solid' },
      });

      slide5.addText(`${i + 1}`, {
        x: 0.7,
        y: y + 0.35,
        w: 0.5,
        h: 0.6,
        fontSize: 20,
        bold: true,
        color: COLORS.secondary,
      });

      slide5.addText(rec.region, {
        x: 1.3,
        y: y + 0.15,
        w: 5,
        h: 0.5,
        fontSize: 22,
        bold: true,
        color: COLORS.light,
      });

      slide5.addText(`+${Math.round(rec.potentialGain)} potential quotes`, {
        x: 7,
        y: y + 0.15,
        w: 2.3,
        h: 0.5,
        fontSize: 16,
        bold: true,
        color: COLORS.secondary,
        align: 'right',
      });

      slide5.addText(
        `Current: ${rec.tpRate.toFixed(1)}%  |  Avg: ${rec.departmentAvgRate.toFixed(1)}%  |  Gap: ${Math.abs(rec.deviation).toFixed(1)}pp  |  ${rec.trips} passthroughs`,
        {
          x: 1.3,
          y: y + 0.7,
          w: 8,
          h: 0.4,
          fontSize: 14,
          color: COLORS.muted,
        }
      );
    });
  } else {
    slide5.addText('No significant P>Q improvement opportunities identified.', {
      x: 0.5,
      y: 2,
      w: 9,
      h: 0.5,
      fontSize: 18,
      color: COLORS.muted,
      align: 'center',
      italic: true,
    });
  }

  // Slide 6: Agent Performance - Top Performers
  const slide6 = pptx.addSlide();
  slide6.background = { color: '0F172A' };

  slide6.addText('Top Performers', {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.8,
    fontSize: 32,
    bold: true,
    color: COLORS.success,
  });

  slide6.addText('Agents leading regional conversion', {
    x: 0.5,
    y: 0.9,
    w: 9,
    h: 0.4,
    fontSize: 16,
    color: COLORS.muted,
  });

  if (data.topAgents.length > 0) {
    data.topAgents.forEach((agent, i) => {
      const y = 1.5 + i * 1.4;

      // Medal emoji based on position
      const medal = i === 0 ? '🥇' : i === 1 ? '🥈' : '🥉';

      slide6.addText(medal, {
        x: 0.5,
        y: y + 0.2,
        w: 0.6,
        h: 0.6,
        fontSize: 28,
      });

      slide6.addText(agent.name, {
        x: 1.2,
        y: y + 0.1,
        w: 5,
        h: 0.5,
        fontSize: 24,
        bold: true,
        color: COLORS.light,
      });

      slide6.addText(`${agent.tpRate.toFixed(1)}%`, {
        x: 7.5,
        y: y + 0.1,
        w: 2,
        h: 0.5,
        fontSize: 28,
        bold: true,
        color: COLORS.success,
        align: 'right',
      });

      slide6.addText(`${agent.trips} trips`, {
        x: 7.5,
        y: y + 0.6,
        w: 2,
        h: 0.3,
        fontSize: 14,
        color: COLORS.muted,
        align: 'right',
      });

      if (agent.regions.length > 0) {
        slide6.addText(`Strong: ${agent.regions.join(', ')}`, {
          x: 1.2,
          y: y + 0.7,
          w: 6,
          h: 0.4,
          fontSize: 14,
          color: COLORS.muted,
        });
      }
    });
  }

  // Slide 7: Agent Performance - Development Focus
  const slide7 = pptx.addSlide();
  slide7.background = { color: '0F172A' };

  slide7.addText('Development Focus', {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.8,
    fontSize: 32,
    bold: true,
    color: COLORS.warning,
  });

  slide7.addText('Agents with coaching opportunities', {
    x: 0.5,
    y: 0.9,
    w: 9,
    h: 0.4,
    fontSize: 16,
    color: COLORS.muted,
  });

  if (data.bottomAgents.length > 0) {
    data.bottomAgents.forEach((agent, i) => {
      const y = 1.5 + i * 1.4;

      slide7.addShape('rect', {
        x: 0.5,
        y: y,
        w: 9,
        h: 1.2,
        fill: { color: '1E293B' },
        line: { color: '475569', width: 1 },
      });

      slide7.addText(`${i + 1}`, {
        x: 0.7,
        y: y + 0.35,
        w: 0.5,
        h: 0.5,
        fontSize: 18,
        bold: true,
        color: COLORS.warning,
      });

      slide7.addText(agent.name, {
        x: 1.3,
        y: y + 0.15,
        w: 5,
        h: 0.5,
        fontSize: 22,
        bold: true,
        color: COLORS.light,
      });

      slide7.addText(`${agent.tpRate.toFixed(1)}%`, {
        x: 7.5,
        y: y + 0.15,
        w: 2,
        h: 0.5,
        fontSize: 24,
        bold: true,
        color: COLORS.danger,
        align: 'right',
      });

      slide7.addText(`${agent.trips} trips`, {
        x: 7.5,
        y: y + 0.55,
        w: 2,
        h: 0.3,
        fontSize: 14,
        color: COLORS.muted,
        align: 'right',
      });

      if (agent.focusRegions.length > 0) {
        slide7.addText(`Focus: ${agent.focusRegions.join(', ')}`, {
          x: 1.3,
          y: y + 0.7,
          w: 6,
          h: 0.4,
          fontSize: 14,
          color: COLORS.warning,
        });
      }
    });
  }

  // Slide 8: Actions & Next Steps
  const slide8 = pptx.addSlide();
  slide8.background = { color: '0F172A' };

  slide8.addText('Actions & Next Steps', {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.8,
    fontSize: 32,
    bold: true,
    color: COLORS.primary,
  });

  const actions = [
    { text: 'Review training materials for focus destinations', icon: '📚' },
    { text: 'Schedule 1:1s with development focus agents', icon: '📅' },
    { text: 'Share best practices from top performers', icon: '🌟' },
    { text: 'Update destination knowledge resources', icon: '🗺️' },
    { text: 'Set improvement targets for next review', icon: '🎯' },
  ];

  actions.forEach((action, i) => {
    const y = 1.2 + i * 0.8;

    slide8.addText(action.icon, {
      x: 0.5,
      y: y,
      w: 0.6,
      h: 0.6,
      fontSize: 24,
    });

    slide8.addText(action.text, {
      x: 1.2,
      y: y + 0.1,
      w: 8,
      h: 0.5,
      fontSize: 20,
      color: COLORS.light,
    });
  });

  // Slide 9: Thank You / End Slide
  const slide9 = pptx.addSlide();
  slide9.background = { color: '0F172A' };

  slide9.addText('Thank You!', {
    x: 0.5,
    y: 2,
    w: 9,
    h: 1,
    fontSize: 48,
    bold: true,
    color: COLORS.light,
    align: 'center',
  });

  slide9.addText("Let's make it a great month! 🚀", {
    x: 0.5,
    y: 3.2,
    w: 9,
    h: 0.6,
    fontSize: 24,
    color: COLORS.primary,
    align: 'center',
  });

  slide9.addText('Generated by GTT KPI Report', {
    x: 0.5,
    y: 4.8,
    w: 9,
    h: 0.4,
    fontSize: 12,
    color: COLORS.muted,
    align: 'center',
    italic: true,
  });

  // Save the file
  await pptx.writeFile({ fileName: `Department_Champs_${data.program.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pptx` });
};
